const db=require('../config/db');
exports.vehiculos=async(_,res)=>{try{res.json((await db.query('SELECT * FROM vehiculos WHERE activo=true ORDER BY placa')).rows)}catch(e){res.status(500).json({message:e.message})}};
exports.conductores=async(_,res)=>{try{res.json((await db.query('SELECT * FROM conductores WHERE activo=true ORDER BY nombre')).rows)}catch(e){res.status(500).json({message:e.message})}};
exports.combustibles=async(_,res)=>{try{res.json((await db.query('SELECT * FROM combustibles WHERE activo=true ORDER BY id')).rows)}catch(e){res.status(500).json({message:e.message})}};
exports.addVehiculo=async(req,res)=>{try{const {placa,marca,modelo,anio,tipo,combustible}=req.body;if(!placa)return res.status(400).json({message:'La placa es obligatoria.'});const q=await db.query('INSERT INTO vehiculos(placa,marca,modelo,anio,tipo,combustible) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[placa.trim().toUpperCase(),marca||null,modelo||null,anio||null,tipo||'Vehículo',combustible||null]);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({message:e.code==='23505'?'La placa ya existe.':e.message})}};
exports.removeVehiculo=async(req,res)=>{try{await db.query('UPDATE vehiculos SET activo=false WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}};
exports.addConductor=async(req,res)=>{try{const {nombre,documento,telefono}=req.body;if(!nombre)return res.status(400).json({message:'El nombre es obligatorio.'});const q=await db.query('INSERT INTO conductores(nombre,documento,telefono) VALUES($1,$2,$3) RETURNING *',[nombre.trim(),documento||null,telefono||null]);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({message:e.code==='23505'?'El conductor ya existe.':e.message})}};
exports.removeConductor=async(req,res)=>{try{await db.query('UPDATE conductores SET activo=false WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}};
exports.addCombustible=async(req,res)=>{try{const {codigo,nombre,precio_referencia,unidad}=req.body;if(!codigo||!nombre)return res.status(400).json({message:'Código y nombre son obligatorios.'});const q=await db.query('INSERT INTO combustibles(codigo,nombre,precio_referencia,unidad) VALUES($1,$2,$3,$4) RETURNING *',[codigo.trim().toUpperCase(),nombre.trim(),Number(precio_referencia||0),unidad||'GALÓN']);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({message:e.code==='23505'?'El combustible ya existe.':e.message})}};
exports.removeCombustible=async(req,res)=>{try{await db.query('UPDATE combustibles SET activo=false WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}};
exports.dashboard=async(_,res)=>{try{const [t,v,g,s,monthly,byFuel,byVehicle]=await Promise.all([
 db.query('SELECT COUNT(*) n FROM abastecimientos'),db.query('SELECT COUNT(*) n FROM vehiculos WHERE activo=true'),db.query('SELECT COALESCE(SUM(galones),0) n FROM abastecimientos'),db.query("SELECT COALESCE(SUM(importe),0) n FROM abastecimientos WHERE date_trunc('month',fecha)=date_trunc('month',CURRENT_DATE)"),db.query("SELECT to_char(date_trunc('month',fecha),'YYYY-MM') mes,COALESCE(SUM(importe),0) gasto,COALESCE(SUM(galones),0) galones,COALESCE(SUM(recorrido),0) km FROM abastecimientos GROUP BY 1 ORDER BY 1"),db.query('SELECT combustible,COALESCE(SUM(galones),0) galones,COALESCE(SUM(importe),0) gasto FROM abastecimientos GROUP BY combustible ORDER BY gasto DESC'),db.query('SELECT v.placa,COALESCE(SUM(a.galones),0) galones,COALESCE(SUM(a.importe),0) gasto,COALESCE(SUM(a.recorrido),0) km FROM abastecimientos a JOIN vehiculos v ON v.id=a.vehiculo_id GROUP BY v.placa ORDER BY gasto DESC')]);res.json({registros:Number(t.rows[0].n),vehiculos:Number(v.rows[0].n),galones:Number(g.rows[0].n),gastoMes:Number(s.rows[0].n),monthly:monthly.rows,byFuel:byFuel.rows,byVehicle:byVehicle.rows})}catch(e){res.status(500).json({message:e.message})}};
